---
name: "SLURM"
partition: "Hide HPC details for ICLR Double Blind review"
job-name: "metaworld_seq_entire"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 900
gpus_per_rep: 1
scheduler: "Hide HPC details for ICLR Double Blind review"
sbatch_args:
  gres: "gpu:4"
  account: "Hide HPC details for ICLR Double Blind review"

experiment_copy_src:
  - "../" # RL Code base
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: metaworld_seq_entire
import_path: "./shared_meta.yaml"
import_exp: "metaworld_seq_entire"

# cw2 config
repetitions: 8      # Number of random seeds
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 25000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 2
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations

# Hyperparameters tuning configs

grid:
#  agent:
#    args:
#      epochs_policy: [15, 30, 50]
#      epochs_critic: [15, 30, 50]
#      lr_policy: [5e-5, 1e-4, 3e-4, 1e-3]
#      lr_critic: [5e-5, 1e-4, 3e-4, 1e-3]
#  critic:
#    args:
#      n_layer: [1, 2]
#      n_head: [1, 2, 4, 8]
#      n_embd: [64, 128, 256]
#  projection:
#    args:
#      mean_bound: [0.002, 0.005, 0.01, 0.02]
#      cov_bound: [0.0002, 0.0005, 0.001, 0.002]
#      trust_region_coeff: [0.2, 1.0, 5.0, 25.0]
  sampler:
    args:
      env_id:
        [
          "metaworld_ProDMP_TCE/assembly-v2",
          "metaworld_ProDMP_TCE/pick-out-of-hole-v2",
          "metaworld_ProDMP_TCE/plate-slide-v2",
          "metaworld_ProDMP_TCE/plate-slide-back-v2",
          "metaworld_ProDMP_TCE/plate-slide-side-v2",
          "metaworld_ProDMP_TCE/plate-slide-back-side-v2",
          "metaworld_ProDMP_TCE/bin-picking-v2",
          "metaworld_ProDMP_TCE/hammer-v2",
          "metaworld_ProDMP_TCE/sweep-into-v2",
          "metaworld_ProDMP_TCE/box-close-v2",
          "metaworld_ProDMP_TCE/button-press-v2",
          "metaworld_ProDMP_TCE/button-press-wall-v2",
          "metaworld_ProDMP_TCE/button-press-topdown-v2",
          "metaworld_ProDMP_TCE/button-press-topdown-wall-v2",
          "metaworld_ProDMP_TCE/coffee-button-v2",
          "metaworld_ProDMP_TCE/coffee-pull-v2",
          "metaworld_ProDMP_TCE/coffee-push-v2",
          "metaworld_ProDMP_TCE/dial-turn-v2",
          "metaworld_ProDMP_TCE/disassemble-v2",
          "metaworld_ProDMP_TCE/door-close-v2",
          "metaworld_ProDMP_TCE/door-lock-v2",
          "metaworld_ProDMP_TCE/door-open-v2",
          "metaworld_ProDMP_TCE/door-unlock-v2",
          "metaworld_ProDMP_TCE/hand-insert-v2",
          "metaworld_ProDMP_TCE/drawer-close-v2",
          "metaworld_ProDMP_TCE/drawer-open-v2",
          "metaworld_ProDMP_TCE/faucet-open-v2",
          "metaworld_ProDMP_TCE/faucet-close-v2",
          "metaworld_ProDMP_TCE/handle-press-side-v2",
          "metaworld_ProDMP_TCE/handle-press-v2",
          "metaworld_ProDMP_TCE/handle-pull-side-v2",
          "metaworld_ProDMP_TCE/handle-pull-v2",
          "metaworld_ProDMP_TCE/lever-pull-v2",
          "metaworld_ProDMP_TCE/peg-insert-side-v2",
          "metaworld_ProDMP_TCE/pick-place-wall-v2",
          "metaworld_ProDMP_TCE/reach-v2",
          "metaworld_ProDMP_TCE/push-back-v2",
          "metaworld_ProDMP_TCE/push-v2",
          "metaworld_ProDMP_TCE/pick-place-v2",
          "metaworld_ProDMP_TCE/peg-unplug-side-v2",
          "metaworld_ProDMP_TCE/soccer-v2",
          "metaworld_ProDMP_TCE/stick-push-v2",
          "metaworld_ProDMP_TCE/stick-pull-v2",
          "metaworld_ProDMP_TCE/push-wall-v2",
          "metaworld_ProDMP_TCE/reach-wall-v2",
          "metaworld_ProDMP_TCE/shelf-place-v2",
          "metaworld_ProDMP_TCE/sweep-v2",
          "metaworld_ProDMP_TCE/window-open-v2",
          "metaworld_ProDMP_TCE/window-close-v2",
          "metaworld_ProDMP_TCE/basketball-v2"
        ]
