# cw2 config
name: metaworld_seq_entire
import_path: "./shared_meta.yaml"
import_exp: "metaworld_seq_entire"

repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: &iterations 25000
num_checkpoints: 1


# Hardware specific parameters
params:

  sampler:
    args:
      num_env_train: 4
      num_env_test: 8
      episodes_per_train_env: 1
      episodes_per_test_env: 5
  projection:
    args:
      total_train_steps: *iterations