---
name: "SLURM"
partition: "Hide HPC details for ICLR Double Blind review"
job-name: "hopper_seq_entire"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 800
gpus_per_rep: 1
scheduler: "Hide HPC details for ICLR Double Blind review"
sbatch_args:
  gres: "gpu:4"
  account: "Hide HPC details for ICLR Double Blind review"

experiment_copy_src:
  - "../" # RL Code base
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: hopper_seq_entire
import_path: "./shared_hopper.yaml"
import_exp: "hopper_seq_entire"

# cw2 config
repetitions: 8      # Number of random seeds
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 15000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 1
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations

# Hyperparameters tuning configs

#grid:
#  agent:
#    args:
#      epochs_policy: [5, 10, 15]
#      epochs_critic: [10, 20, 30]
#      lr_policy: [1.5e-4, 3e-4, 6e-4]
#      lr_critic: [1.5e-4, 3e-4, 6e-4, 1e-3]
#  critic:
#    args:
#      n_layer: [1, 2]
#      n_head: [1, 2, 4, 8]
#      n_embd: [64, 128, 256]
#  projection:
#    args:
#      mean_bound: [0.025, 0.05]
#      cov_bound: [0.0025, 0.005, 0.01]
#      trust_region_coeff: [0.2, 1.0, 5.0, 25.0]
